sudo: false
language: rust

# TODO: use rustup to pin version?
rust:
    - nightly

matrix:
    include:
        # host agnostic tests (linux)
        - env: PRGTARGET="host"
        # thumbv7em build
        - env: PRGTARGET=thumbv7em-none-eabi

script: ./quick_build.sh
