sudo: false
language: rust

# TODO: use rustup to pin version?
rust: nightly

addons:
    apt:
        sources:
            - debian-sid
        packages:
            - gcc-arm-none-eabi

matrix:
    include:
        # host agnostic tests (linux)
        - env: PRGTARGET=test
        # thumbv7em build
        - env: PRGTARGET=thumbv7m-release

# if no env from matrix, doc... otherwise, build the target
script:  if [ -z "$PRGTARGET" ]; then make doc-upload; else make $PRGTARGET; fi
