sudo: false
language: rust

# TODO: use rustup to pin version?
rust:
    - nightly

matrix:
    # host agnostic tests (linux)
    - env: PRGTARGET="host"
    # thumbv7em build
    - env: PRGTARGET=thumbv7em-none-eabi

# TODO: add tests
env:
    # add the build_targets directory to the path
    - RUST_TARGET_PATH=$RUST_TARGET_PATH:./build_targets

script:
    - echo "USING TARGET: $PRGTARGET"
    - if [[ "$PRGTARGET" == "host" ]]; then cargo test --verbose; fi
    - if [[ "$PRGTARGET" != "host" ]]; then cargo build --verbose --target $PRGTARGET; fi

