sudo: false
language: rust

# TODO: use rustup to pin version?
rust:
    - nightly

matrix:
    # host agnostic tests (linux)
    - env: PRGTARGET="host"
    # thumbv7em build
    - env: PRGTARGET=thumbv7em-none-eabi

# TODO: add tests
env:
    # add the build_targets directory to the path
    - RUST_TARGET_PATH=$RUST_TARGET_PATH:./build_targets

script: ./quick_build.sh
