sudo: false
language: rust

# TODO: use rustup to pin version?
rust: nightly

matrix:
    include:
        # host agnostic tests (linux)
        - env: PRGTARGET=test
        # thumbv7em build
        - env: PRGTARGET=thumbv7m-none-eabi

script: ./quick_build.sh

#TODO: hmmm, need to enable all configs and will this build docs for every entry in the matrix?
after_success:
    - cargo doc
    - ./scripts/ghp_upload.sh
