sudo: false
language: rust

# TODO: use rustup to pin version?
rust:
    - nightly

matrix:
    # host agnostic tests (linux)
    - env: TARGET=$TESTTARGET
    # thumbv7em build
    - env: TARGET=thumbv7em-none-eabi

# TODO: add tests
env:
    - TESTTARGET=x86_64-unknown-linux-gnu
    # add the build_targets directory to the path
    - RUST_TARGET_PATH=$RUST_TARGET_PATH:./build_targets

script:
    - echo "--------------------------------------------------"
    - echo ""
    - echo " building target: $TARGET"
    - echo ""
    - echo "--------------------------------------------------"

    - if [[ "$TARGET" == "$TESTTARGET" ]]; then cargo test --verbose; fi
    - if [[ "$TARGET" != "$TESTTARGET" ]]; then cargo build --verbose --target $TARGET; fi

